apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-demo
spec:
  restartPolicy: Always
  initContainers:
  - name: init-permissions
    image: busybox:1.36
    command:
      - sh
      - -c
      - mkdir -p /var/log/nginx && touch /var/log/nginx/access.log && chown -R 1000:1000 /var/log/nginx
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
  containers:
  - name: web
    image: nginx:1.25
    ports:
      - containerPort: 80
        name: http
    env:
      - name: LISTEN_PORT
        value: "80"
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 15
      periodSeconds: 20
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  - name: log-collector
    image: busybox:1.36
    command:
      - sh
      - -c
      - tail -F /var/log/nginx/access.log
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    livenessProbe:
      exec:
        command:
          - pgrep
          - tail
      initialDelaySeconds: 10
      periodSeconds: 10
  volumes:
    - name: shared-logs
      emptyDir: {}