apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    env: demo
    tier: frontend
    type: web
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  nodeName: 
    cka-cluster3-worker